USE memdemo;
GO

CREATE TABLE MemoryTable ( ID INTEGER NOT NULL PRIMARY KEY NONCLUSTERED HASH WITH ( BUCKET_COUNT = 1000000),
Date_Value DATETIME NULL,
)
WITH ( MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA);

GO

CREATE TABLE DiskTable (ID INTEGER NOT NULL PRIMARY KEY NONCLUSTERED,
Date_Value DATETIME NOT NULL );
GO

-- LET US NOW DO A COMPARISSON BETWEEN DISK NORMAL TABLES AND MEMORY OPTIMIZED TABLES--
--TRANSACTION WITH A NORMAL TABLE--
BEGIN TRANSACTION 
DECLARE @DiskID int = 1
WHILE @DiskID < 500000
BEGIN
INSERT INTO dbo.DiskTable 
VALUES (@DiskID, GETDATE())
SET @DiskID += 1
END
COMMIT;
GO
--TRANSACTION WITH MEMORY-OPTIMIZED TABLE--
BEGIN TRANSACTION 
DECLARE @DiskID int = 1
WHILE @DiskID < 500000
BEGIN
INSERT INTO dbo.MemoryTable
VALUES (@DiskID, GETDATE())
SET @DiskID += 1
END
COMMIT;
GO